backend:
  name: github
  repo: mimof9/vn
  branch: main
publish_mode: editorial_workflow
media_folder: "docs/.vuepress/public/uploads"
public_folder: "/uploads"
collections:
  - name: "Pages"
    label: "page"
    files:
      - label: "Home Page"
        name: "home"
        file: "docs/README.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "docs/_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # {{year}}-{{month}}-{{day}}-{{slug}} Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "文件名", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "精选图片", name: "thumbnail", widget: "image"}
      - {label: "正文", name: "body", widget: "markdown"}
